"""created profile

Revision ID: 32e11586ef40
Revises: 3df684134cd8
Create Date: 2025-05-07 19:17:12.928281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32e11586ef40'
down_revision: Union[str, None] = '3df684134cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('disabled', sa.Boolean(), nullable=False))
    op.add_column('profile', sa.Column('disabled', sa.Boolean(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'disabled')
    # op.drop_column('profile', 'disabled')
    # ### end Alembic commands ###
